export const ticket = [
 {
  "departureTime": "06.00",
  "arriveTime": "07.00",
  "flightTime": "1 saat",
  "departureAirport": "Adana",
  "departureAirportCode": "ADA",
  "arriveAirport": "Ankara",
  "arriveAirportCode": "ESB",
  "price": "1000TL",
  "date1": "21.08.2023",
  "id": "1"
 },
 {
  "departureTime": "06.00",
  "arriveTime": "07.00",
  "flightTime": "1 saat",
  "departureAirport": "Ankara",
  "departureAirportCode": "ESB",
  "arriveAirport": "Adana",
  "arriveAirportCode": "ADA",
  "price": "1000TL",
  "date1": "25.08.2023",
  "id": "2"
 },
 {
  "departureTime": "08.00",
  "arriveTime": "09.00",
  "flightTime": "1 saat",
  "departureAirport": "Ankara",
  "departureAirportCode": "ESB",
  "arriveAirport": "Antalya",
  "arriveAirportCode": "AYT",
  "price": "1500TL",
  "date1": "01.09.2023",
  "id": "3"
 },
 {
  "departureTime": "08.00",
  "arriveTime": "09.00",
  "flightTime": "1 saat",
  "departureAirport": "Antalya",
  "departureAirportCode": "AYT",
  "arriveAirport": "Ankara",
  "arriveAirportCode": "ESB",
  "price": "1500TL",
  "date1": "05.09.2023",
  "id": "4"
 },
 {
  "departureTime": "10.00",
  "arriveTime": "11.00",
  "flightTime": "1 saat",
  "departureAirport": "Antalya",
  "departureAirportCode": "AYT",
  "arriveAirport": "Eskişehir",
  "arriveAirportCode": "AOE",
  "price": "1300TL",
  "date1": "26.08.2023",
  "id": "5"
 },
 {
  "departureTime": "10.00",
  "arriveTime": "11.00",
  "flightTime": "1 saat",
  "departureAirport": "Eskişehir",
  "departureAirportCode": "AOE",
  "arriveAirport": "Antalya",
  "arriveAirportCode": "AYT",
  "price": "1300TL",
  "date1": "30.08.2023",
  "id": "6"
 },
 {
  "departureTime": "12.00",
  "arriveTime": "13.00",
  "flightTime": "1 saat",
  "departureAirport": "Eskişehir",
  "departureAirportCode": "AOE",
  "arriveAirport": "İstanbul Havalimanı",
  "arriveAirportCode": "IST",
  "price": "900TL",
  "date1": "06.09.2023",
  "id": "7"
 },
 {
  "departureTime": "12.00",
  "arriveTime": "13.00",
  "flightTime": "1 saat",
  "departureAirport": "Eskişehir",
  "departureAirportCode": "AOE",
  "arriveAirport": "Antalya",
  "arriveAirportCode": "AYT",
  "price": "900TL",
  "date1": "10.09.2023",
  "id": "8"
 },
 {
  "departureTime": "14.00",
  "arriveTime": "15.00",
  "flightTime": "1 saat",
  "departureAirport": "İstanbul Sabiha Gökçen",
  "departureAirportCode": "SAW",
  "arriveAirport": "İzmir",
  "arriveAirportCode": "ADB",
  "price": "1200TL",
  "date1": "03.09.2023",
  "id": "9"
 },
 {
  "departureTime": "14.00",
  "arriveTime": "15.00",
  "flightTime": "1 saat",
  "departureAirport": "İzmir",
  "departureAirportCode": "ADB",
  "arriveAirport": "İstanbul Sabiha Gökçen",
  "arriveAirportCode": "SAW",
  "price": "1200TL",
  "date1": "07.09.2023",
  "id": "10"
 },
 {
  "departureTime": "08.00",
  "arriveTime": "09.00",
  "flightTime": "1 saat",
  "departureAirport": "Adana",
  "departureAirportCode": "ADA",
  "arriveAirport": "Ankara",
  "arriveAirportCode": "ESB",
  "price": "1000TL",
  "date1": "21.08.2023",
  "id": "11"
 },
 {
  "departureTime": "08.00",
  "arriveTime": "09.00",
  "flightTime": "1 saat",
  "departureAirport": "Ankara",
  "departureAirportCode": "ESB",
  "arriveAirport": "Adana",
  "arriveAirportCode": "ADA",
  "price": "1000TL",
  "date1": "25.08.2023",
  "id": "12"
 },
 {
  "departureTime": "10.00",
  "arriveTime": "11.00",
  "flightTime": "1 saat",
  "departureAirport": "Ankara",
  "departureAirportCode": "ESB",
  "arriveAirport": "Antalya",
  "arriveAirportCode": "AYT",
  "price": "1500TL",
  "date1": "01.09.2023",
  "id": "13"
 },
 {
  "departureTime": "10.00",
  "arriveTime": "11.00",
  "flightTime": "1 saat",
  "departureAirport": "Antalya",
  "departureAirportCode": "AYT",
  "arriveAirport": "Ankara",
  "arriveAirportCode": "ESB",
  "price": "1500TL",
  "date1": "05.09.2023",
  "id": "14"
 },
 {
  "departureTime": "12.00",
  "arriveTime": "13.00",
  "flightTime": "1 saat",
  "departureAirport": "Antalya",
  "departureAirportCode": "AYT",
  "arriveAirport": "Eskişehir",
  "arriveAirportCode": "AOE",
  "price": "1300TL",
  "date1": "26.08.2023",
  "id": "15"
 },
 {
  "departureTime": "12.00",
  "arriveTime": "13.00",
  "flightTime": "1 saat",
  "departureAirport": "Eskişehir",
  "departureAirportCode": "AOE",
  "arriveAirport": "Antalya",
  "arriveAirportCode": "AYT",
  "price": "1300TL",
  "date1": "30.08.2023",
  "id": "16"
 },
 {
  "departureTime": "14.00",
  "arriveTime": "15.00",
  "flightTime": "1 saat",
  "departureAirport": "Eskişehir",
  "departureAirportCode": "AOE",
  "arriveAirport": "İstanbul Havalimanı",
  "arriveAirportCode": "IST",
  "price": "900TL",
  "date1": "06.09.2023",
  "id": "17"
 },
 {
  "departureTime": "14.00",
  "arriveTime": "15.00",
  "flightTime": "1 saat",
  "departureAirport": "Eskişehir",
  "departureAirportCode": "AOE",
  "arriveAirport": "Antalya",
  "arriveAirportCode": "AYT",
  "price": "900TL",
  "date1": "10.09.2023",
  "id": "18"
 },
 {
  "departureTime": "16.00",
  "arriveTime": "17.00",
  "flightTime": "1 saat",
  "departureAirport": "İstanbul Sabiha Gökçen",
  "departureAirportCode": "SAW",
  "arriveAirport": "İzmir",
  "arriveAirportCode": "ADB",
  "price": "1200TL",
  "date1": "03.09.2023",
  "id": "19"
 },
 {
  "departureTime": "16.00",
  "arriveTime": "17.00",
  "flightTime": "1 saat",
  "departureAirport": "İzmir",
  "departureAirportCode": "ADB",
  "arriveAirport": "İstanbul Sabiha Gökçen",
  "arriveAirportCode": "SAW",
  "price": "1200TL",
  "date1": "07.09.2023",
  "id": "20"
 },
 {
  "departureTime": "15.00",
  "arriveTime": "16.00",
  "flightTime": "1 saat",
  "departureAirport": "Malatya",
  "departureAirportCode": "MLX",
  "arriveAirport": "Muğla Dalaman",
  "arriveAirportCode": "DLM",
  "price": "2000TL",
  "date1": "21.09.2023",
  "id": "21"
 },
 {
  "departureTime": "17.00",
  "arriveTime": "18.00",
  "flightTime": "1 saat",
  "departureAirport": "Malatya",
  "departureAirportCode": "MLX",
  "arriveAirport": "Muğla Dalaman",
  "arriveAirportCode": "DLM",
  "price": "2000TL",
  "date1": "21.09.2023",
  "id": "22"
 },
 {
  "departureTime": "19.00",
  "arriveTime": "20.00",
  "flightTime": "1 saat",
  "departureAirport": "Malatya",
  "departureAirportCode": "MLX",
  "arriveAirport": "Muğla Dalaman",
  "arriveAirportCode": "DLM",
  "price": "2000TL",
  "date1": "21.09.2023",
  "id": "23"
 },
 {
  "departureTime": "21.00",
  "arriveTime": "22.00",
  "flightTime": "1 saat",
  "departureAirport": "Malatya",
  "departureAirportCode": "MLX",
  "arriveAirport": "Muğla Dalaman",
  "arriveAirportCode": "DLM",
  "price": "2000TL",
  "date1": "21.09.2023",
  "id": "24"
 },
 {
  "departureTime": "23.00",
  "arriveTime": "00.00",
  "flightTime": "1 saat",
  "departureAirport": "Malatya",
  "departureAirportCode": "MLX",
  "arriveAirport": "Muğla Dalaman",
  "arriveAirportCode": "DLM",
  "price": "2000TL",
  "date1": "21.09.2023",
  "id": "25"
 },
 {
  "departureTime": "15.00",
  "arriveTime": "16.00",
  "flightTime": "1 saat",
  "departureAirport": "Samsun",
  "departureAirportCode": "SZF",
  "arriveAirport": "Sivas",
  "arriveAirportCode": "VAS",
  "price": "1700TL",
  "date1": "30.09.2023",
  "id": "26"
 },
 {
  "departureTime": "17.00",
  "arriveTime": "18.00",
  "flightTime": "1 saat",
  "departureAirport": "Samsun",
  "departureAirportCode": "SZF",
  "arriveAirport": "Sivas",
  "arriveAirportCode": "VAS",
  "price": "1700TL",
  "date1": "30.09.2023",
  "id": "27"
 },
 {
  "departureTime": "19.00",
  "arriveTime": "20.00",
  "flightTime": "1 saat",
  "departureAirport": "Samsun",
  "departureAirportCode": "SZF",
  "arriveAirport": "Sivas",
  "arriveAirportCode": "VAS",
  "price": "1700TL",
  "date1": "30.09.2023",
  "id": "28"
 },
 {
  "departureTime": "21.00",
  "arriveTime": "22.00",
  "flightTime": "1 saat",
  "departureAirport": "Samsun",
  "departureAirportCode": "SZF",
  "arriveAirport": "Sivas",
  "arriveAirportCode": "VAS",
  "price": "1700TL",
  "date1": "30.09.2023",
  "id": "29"
 },
 {
  "departureTime": "23.00",
  "arriveTime": "00.00",
  "flightTime": "1 saat",
  "departureAirport": "Samsun",
  "departureAirportCode": "SZF",
  "arriveAirport": "Sivas",
  "arriveAirportCode": "VAS",
  "price": "1700TL",
  "date1": "30.09.2023",
  "id": "29"
 }
]